### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gladys123**

### CODE REVIEW

**Comment by samdroid-apps** [comment]
No, you can't do that.  Do you have permission from the copyright holders
to re-lisence their code?

**Comment by gladys123** [comment]
It counts even if they're intoxicated right?

**Comment by i5o** [comment]
I feel hacktoberfest.

**Comment by i5o** [comment]
smell \*

**Comment by gladys123** [comment]
@i5o XD

**Comment by chaityabshah** [comment]
@gladys123 Lol did you get credit for it? http://hf.heidilabs.com/
my friends did theirs today and didnt get it :\

**Comment by anurag-ks** [comment]
This is bad, I don't think @gladys123 you got the actual motive of hacktoberfest.

**Comment by vipulroxx** [comment]
lalallala

**Comment by anurag-ks** [comment]
and btw I think you're late ;)

**Pull request merged**
